### ISSUE TITLE
Use HTTPS for libdiscid

### ISSUE THREAD

**Issue by hadess** [flathub/org.musicbrainz.Picard#45]
Releases are available on github:
https://github.com/metabrainz/libdiscid/releases

**Comment by bochecha** [comment]
Those are a bit different since they are the autogenerated tarballs from Github, so they don't have the stuff generated by the autotools (e.g the `configure` script)

It shouldn't be that much of a problem though, especially since we should move it to CMake anyway.

Thanks for the report, do you think you'll have time to send a pull request?

**Comment by hadess** [comment]
I've had my fill of builds this morning, but this might help:
https://gitlab.gnome.org/GNOME/sound-juicer/blob/master/build-aux/org.gnome.SoundJuicer.json#L96

**Comment by phw** [comment]
Just want to point out that the ones from MB servers are kind of the official source releases. As noted above the tarballs on Github are "just" the default generated by Github. But use whatever works for you.

**Comment by hadess** [comment]
> Just want to point out that the ones from MB servers are kind of the official source releases. As noted above the tarballs on Github are "just" the default generated by Github. But use whatever works for you.

The Github repository is the canonical repository for libdiscid, right?

**Comment by phw** [comment]
> The Github repository is the canonical repository for libdiscid, right?

Yes, that's right
